# Generated by Django 4.2.7 on 2024-12-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_theater_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
