# Generated by Django 4.2.7 on 2024-12-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
    ]
